name: timely
description: A time tracking application


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  bubble_tab_indicator: ^0.1.4
  flutter_svg_provider: ^0.1.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  flutter_flexible_toast: ^0.1.4
  font_awesome_flutter: ^8.7.1
  provider: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
     - images/

